[#ftl]
[@b.head/]
[@b.toolbar title="修改辅修学生信息"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if minor.persisted]!update?id=${minor.id}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="minor.std.user.code" label="学号" value="${(minor.std.user.code)!}" disabled="disabled"/]
    [@b.textfield name="minor.std.user.name" label="姓名" value="${(minor.std.user.name)!}" disabled="disabled"/]
    [@b.select name="minor.school.id" label="主修学校" value="${(minor.school.id)!}"
    style="width:200px;" items=schools empty="..." required="true"/]
    [@b.textfield name="minor.majorName" label="主修专业" value="${minor.majorName!}" required="true" maxlength="100"/]
    [@b.textfield name="minor.enMajorName" label="主修专业英文名" value="${minor.enMajorName!}"maxlength="100"/]
    [@b.select name="minor.majorCategory.id" label="专业学科门类" value="${(minor.majorCategory.id)!}"
               style="width:200px;" items=majorCategories empty="..." required="true"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
